const screens = {
  welcome: 'Welcome',
  getStarted: 'GetStarted',
  authStack: 'AuthStack',
  resetStack: 'ResetStack',
  appStack: 'AppStack',
  drawerStack: 'DrawerStack',
  bottomTabStack: 'BottomTabStack',
  auth: 'Auth',
  login: 'Login',
  signUp: 'Signup',
  forgotPassword: 'ForgotPassword',
  trial: 'Trial',
  challenges: 'Challenges',
  createChallenge: 'CreateChallenge',
  workouts: 'Workouts',
  exercises: 'Exercises',
  community: 'Community',
  createNewPost: 'CreateNewPost',
  editPost: 'EditPost',
  createNewGroup: 'CreateNewGroup',
  editGroup: 'EditGroup',
  manageCommunity: 'ManageCommunity',
  myFriends: 'MyFriends',
  manageGroups: 'ManageGroups',
  friendRequests: 'FriendRequests',
  groupRequests: 'GroupRequests',
  challengeRequests: 'ChallengeRequests',
  chatScreen: 'ChatScreen',
  favorites: 'Favorites',
  notifications: 'Notifications',
  customWorkout: 'CustomWorkout',
  detail: 'Detail',
};

export {screens};
